fixed/new scripts

diff --git a/src/block b/src/block
--- a/src/block
+++ b/src/block
@@ -5,7 +5,7 @@ cg="\033[0;0m\033[1;32m"
 cb="\033[0;0m\033[1;34m"
 
 help() { printf "${cg}block: print colored blocks
-Usage: block ${cb}value${cg}
+Usage: block ${cb}[conf_file|val]${cg}(conf_file included in test dir)
   ${cb}0:${cg} black 
   ${cb}1:${cg} red 
   ${cb}2:${cg} green 
@@ -14,16 +14,20 @@ Usage: block ${cb}value${cg}
   ${cb}5:${cg} magenta 
   ${cb}6:${cg} cyan 
   ${cb}7:${cg} white
-Example: block ${cb}01234567 76543210${cg}
-Extra Juice: block ${cb}1111105555 2020204000 3030303333 4000402000 5000501111${cg} >> file${cg}
+Example: block ${cb}111105555 2020204000 3030303333 4000402000 5000501111${cg}
 ${cr}Report issues at: https://github.com/manas140/sh/\n" && exit; }
 
 case $1 in 
-  "") printf "${cr}Error: No Value Provided\n" && exit 1;;
+  "") printf "${cr}Error: No File or Value Provided\n" && exit 1;;
   *h|*help) help;;
 esac
 
-for text in "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"; do
+if [ -f $1 ]; then 
+  read=$(cat $1)
+else
+  read="$@"
+fi
+for text in $read; do
   case $text in 
     "") break;;
     *) chars=$(printf "$text" | grep -o .)
@@ -34,3 +38,4 @@ for text in "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"; do
   esac
   printf "\n"
 done
+printf "\033[0;0m\n"
diff --git a/src/cw b/src/cw
--- a/src/cw
+++ b/src/cw
@@ -1,30 +1,38 @@
 #!/bin/sh
 
-#just incase for non sh error
 printf "${cr}"
-#constants
-
+#colors
 cr="\033[1;31m"
 cg="\033[1;32m"
 cb="\033[1;34m"
+#default config variables
 height=720
 width=1280
-ygap=72
-xgap=128
+ygap=100
+xgap=100
 bg="#181818"
-c1="#AB4642"
-c2="#A1B56C"
-c3="#7CAFC2"
+colors="#AB4642 #A1B56C #7CAFC2"
+shape="circle"
 file="wall.png"
 
+#check for convert
 if ! type convert >/dev/null; then
   printf "${cr}Error: Could not find 'convert', Make sure you have ImageMagick installed.\n" && exit 1;
 fi
 
-help() { printf "${cg}cw: create wallpaper
+#better debugging
+count=0
+log() {
+  count=$(($count + 1))
+  printf "$count"
+}
+
+#help function
+help() { printf "${cg}cw: create wallpaper (WIP)
   Usage: cw ${cb}[config_file] [output_file]${cg}(one included in test directory)
 ${cr}Report issues at: https://github.com/manas140/sh/\n" && exit; }
 
+#generate random value between 2 numbers
 random() {
   a=$(( $1 + $(date +%s%N) % $2 ))
   while [ $a -gt $2 ]; do
@@ -33,30 +41,63 @@ random() {
   printf "$a\n"
 }
 
-rrec() {
-  xs=$(random $xgap $(( $width - $xgap )) )
-  xe=$(random $xgap $(( $width - $xgap )) )
-  ys=$(random $ygap $(( $height - $ygap)) )
-  ye=$(random $ygap $(( $height - $ygap)) )
-  printf "$xs $ys $xe $ye\n"
-}
-
+#main
 main() {
-  window_size=$(printf "$width""x""$height")  
-  convert -size "$window_size" xc:$bg -fill $c1 -draw "rectangle $(rrec)" -fill $c2 -draw "rectangle $(rrec)" -fill $c3 -draw "rectangle $(rrec)" -flatten $file
+  #create a shape with random position and size for each color
+  for color in $colors; do
+    case $shape in 
+      circle)
+        #gaps need work
+        xs=$(random $xgap $(( $width - $xgap)) )
+        ys=$(random $ygap $(( $height - $ygap)) )
+        if [ $xs -gt $(($width / 2)) ]; then
+          xe=$(random $xs $(($width - $xgap)))
+        else
+          xe=$(random $xgap $xs)
+        fi
+        if [ $ys -gt $(($height / 2)) ]; then
+          ye=$(random $ys $(($height - $ygap)))
+        else
+          ye=$(random $ygap $ys)
+        fi
+        if [ $ye -gt $xe ]; then
+          xe=$xe
+          ye=$xe
+        else
+          xe=$ye
+          ye=$ye
+        fi;;
+      rectangle)
+        xs=$(random $xgap $width)
+        ys=$(random $ygap $height)
+        xe=$(random $xgap $width)
+        ye=$(random $ygap $height);;
+      *) printf "${cr}Error: Shape Not Supported\n"; exit 1;;
+    esac
+    #save it in a variable 'draw' which will be used later as a argument
+    draw="$draw -fill \"$color\" -draw \"$shape $xs $ys $xe $ye\"";
+  done
+  #convert the variable 'draw' into a working command
+  draw="convert -size \"$width\"x\"$height\" xc:$bg $draw -flatten $file"
+  #run the 'draw' variable
+  eval $draw
   printf "${cg}Wall Generated\n"
 }
 
+#arguments
 case $1 in 
   "") printf "${cr}Error: No File Provided, Using Defaults\n";;
-  *) if [ -f $1 ]; then
+  *) #if file exist source it else show help
+    if [ -f $1 ]; then
       . $(pwd)/$1
     else
       help
     fi;;
 esac
 
+#output_file 
 case $2 in
   *.*) file=$2;;
 esac
+
 main
