fix

diff --git a/src/scr b/src/scr
--- a/src/scr
+++ b/src/scr
@@ -7,6 +7,9 @@ cb="\033[0;0m\033[1;34m"
 if ! type ffmpeg >/dev/null; then
   printf "${cr}Error: Could not find 'ffmpeg', Make sure you have ffmpeg installed.\n" && exit 1;
 fi
+if ! type notify-send >/dev/null; then
+  printf "${cr}Error: Could not find 'ffmpeg', Make sure you have ffmpeg installed.\n" && exit 1;
+fi
 
 help() { printf "${cg}scr: screen shot/record
 Usage: scr ${cb}[s|r] output_file.xyz${cg}
@@ -23,7 +26,11 @@ cf() {
 }
 
 case $1 in
-  *s*) cf $2 && import -window root $file;;
-  *r*) cf $2 && ffmpeg -framerate 60 -f x11grab -i :0.0 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -y -v error -stats $file;;
+  *s*) cf $2 && import -window root $file
+    if type xclip >/dev/null; then
+      xclip -sel clipboard $(pwd)/$file
+      notify-send -i $(pwd)/$file Scr "ScreenShot Copied To Clipboard" 
+    fi;;
+  *r*) cf $2 && notify-send Scr "Screen Recording Started"; ffmpeg -framerate 60 -f x11grab -i :0.0 -pix_fmt yuv420p -c:v libx264 -preset ultrafast -y -v error -stats $file;;
   *) help;;
 esac
